### ISSUE TITLE
 Localization is needed

### ISSUE THREAD

**Issue by lewadedun** [BillyHalley/SailTris#1]
Can you start using the Transifex?

**Comment by BillyHalley** [comment]
Yes, i would like to. I'm new in the field so i'll have to look around and learn how to :)

**Comment by BillyHalley** [comment]
I think i understood that Transifex is not free, i don't have the money to support this project at the moment
If you want you can take a look at the italian translation made by me: https://github.com/BillyHalley/SailTris/blob/master/i18n/translation_it_IT.ts
and edit the empty model with your language translation
https://github.com/BillyHalley/SailTris/blob/master/i18n/translation_%5Bmodel%5D.ts
and pull it here on GitHub or send me an email (ziobilly94@gmail.com)

**Comment by BillyHalley** [comment]
Well, it's free for open source projects, here's the link for transifex https://www.transifex.com/projects/p/sailtris/

**Comment by BillyHalley** [comment]
Well, it's free for open source projects, here's the link for transifex https://www.transifex.com/projects/p/sailtris/
